server:
  port: 8888
  servlet:
    context-path: /webapp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/storage
    username: postgres
    password: postgrespass
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

jwt:
  secret: mkmm'IJ"IOmcldmslaoij;mamldsmaUHu;jds;af98u0jqowjljeo22l1km31;m
  lifetime: 36000000