server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://localhost:8888/
          predicates:
            - Path=/webapp-core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/webapp-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8889/
          predicates:
            - Path=/webapp-cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/webapp-cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:9999/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth
            - JwtAuthFilter

jwt:
  secret: oifh4309f8h324098fh4398gh8h*&TG*#&Gg97rgff98gf983h4f983h487g*&^F&Fu3r

