version: "3.2"

volumes:
  storage-postgres:
    driver: local
  redis:
    driver: local

services:
  postgres:
    image: postgres:12
    container_name: storage-postgres
    volumes:
      - type: volume
        source: storage-postgres
        target: /var/lib/postgresql/dataConfig
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5435:5432"
  redis:
    image: redis
    container_name: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL